Adding RLN keystore
status-im/infra-role-nim-waku pull request #29
Opened 2024-08-16 09:05 UTC by apentori

Linked to : 
* https://github.com/status-im/infra-waku/issues/19

2024-08-16 13:30 UTC, yakimant approved these changes
All good, but I would rather run generate script in Ansible no runtime.

2024-08-19 08:07 UTC, jakubgs requested changes

2024-08-19 08:07 UTC, jakubgs commented on templates/run-node.sh.j2
> +{% endif %}
This is wrong. Those are argument that should be in the Docker compose. This is why there is a distinction between encrypoint and command. This is why God invented `${@}`.

2024-08-19 08:07 UTC, jakubgs commented on templates/docker-compose.yml.j2
> +      - '{{ nim_waku_cont_vol }}/run-node.sh:/opt/run-node.sh:Z'
```suggestion
      - '{{ nim_waku_cont_vol }}/run-node.sh:/opt/entrypoint.sh:Z'
```

2024-08-19 08:07 UTC, jakubgs commented on tasks/config.yml
> +    dest: '{{ nim_waku_cont_vol }}/run-node.sh'
```suggestion
- name: Create node Docker entrypoint
  template:
    src: 'entrypoint.sh.j2'
    dest: '{{ nim_waku_cont_vol }}/entrypoint.sh'
```

2024-08-23 13:14 UTC, Ivansete-status approved these changes
LGTM! Thanks for it! :100: 
I just added a nitpick comment

2024-08-23 13:14 UTC, Ivansete-status commented on templates/docker-compose.yml.j2
> +{# WARNING: Keep sensitive information in run-node.sh. #}
nitpick comment. On the other hand, it seems that we are keeping sensitive info in both the script and the docker-compose.yml file. I think is interesting to keep it in the script file only, to simplify it a little.
```suggestion
{# WARNING: Keep sensitive information in entrypoint.sh. #}
```

2024-08-27 18:24 UTC, jakubgs approved these changes
Nice.

2024-08-27 18:24 UTC, jakubgs commented on templates/docker-compose.yml.j2
> +{# WARNING: Keep sensitive information Docker Compose file. #}
```suggestion
{# WARNING: Keep sensitive information in Docker Compose file. #}
```

2024-08-28 07:52 UTC, merged